### PR TITLE
Ask for a commit with the project setup only

### PR DESCRIPTION
**Pull request by trenpixster**

### CODE REVIEW

**Comment by punnie** [comment]
Did you mean separate _branch_?

**Comment by trenpixster** [comment]
Nope :p

**Comment by punnie** [comment]
Pray explain then, I'm not getting it. :sweat_smile:

**Comment by trenpixster** [comment]
It's to avoid having one commit with all the code mixed, if they separate the project setup (libraries added, generic CSS, etc) and their code, the review will be easier. But if you didn't get it we should rephrase it :smile:

**Comment by punnie** [comment]
I fully agree. With both things. Good point!

**Comment by joao-quiterio** [comment]
Hey Nizar, this seems a bit "prescriptive" in the sense that the commit history (semantic and message of each commit) is one of the aspects we'll be evaluating. Can I close this Pull Request?

**Comment by trenpixster** [comment]
Yes, go ahead 👍

**Pull request closed without merging**
